name = "HomotopyContinuationNext"
uuid = "ec87e138-eaf4-4d78-a098-49d58d8a59d7"
version = "0.1.0-dev"
authors = ["Orjan Ameye"]

[deps]
FixedSizeArrays = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
FixedSizeArrays = "1"
LinearAlgebra = "1"
MultivariatePolynomials = "0.5, 0.6"
Printf = "1"
Random = "1"
Test = "1"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
